name: com_pay
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  image_picker: ^0.8.6+1
  intl: any
  mobile_scanner: ^3.0.0
  package_info: ^2.0.2
  provider: ^6.0.5
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
